@protocol=http
@host = localhost
@port = 3333
@baseUrl = {{protocol}}://{{host}}:{{port}}
@contentType = application/json

@nameStore = Zattini
@logoStore = https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcReqh2k8J_6TcRVG7TNHey0avqJ60goGKMVgakMmgW_4inMKcz8&usqp=CAU
@linkStore = www.Zattini.com.br
@storeId = 5e9649d5f1e7032e779af9c5

@price = 294.989990234375
@title = Tênis Adidas Sensebounce Street Masculino - Preto e Laranja
@image = https://img.vigiadepreco.com.br/bc/83c/f3b6/5d13a/bc83cf3b65d13aad8c0e5effce995d1313635a1ea6f6b18b3084886872928444.jpg
@link = www.adidas.com
@percentage = -5.507113933563232
@productId = 5e964a8cffa5ef2f2a23fdcb

GET {{baseUrl}}/stores/?sortBy=name&descending=true&offset=0&limit=0
Content-Type: {{contentType}}

###
POST {{baseUrl}}/stores
Content-Type: {{contentType}}

{
	"name": "{{nameStore}}",
	"logo": "{{logoStore}}",
	"link": "{{linkStore}}"
}

###
PUT {{baseUrl}}/stores/{{storeId}}
Content-Type: {{contentType}}

{
	"name": "{{nameStore}} 2",
	"logo": "{{logoStore}}",
	"link": "{{linkStore}}"
}

###
GET {{baseUrl}}/stores/{{storeId}}
Content-Type: {{contentType}}

###
DELETE {{baseUrl}}/stores/{{storeId}}
Content-Type: {{contentType}}

###
GET {{baseUrl}}/products
Content-Type: {{contentType}}

###
POST {{baseUrl}}/products
Content-Type: {{contentType}}

{
	"storeId": "{{storeId}}",
	"price": "{{price}}",
	"title":"{{title}}ss",
	"image":"{{image}}",
	"link":"{{link}}",
	"percentage": "{{percentage}}"
}

###
PUT {{baseUrl}}/products/{{productId}}
Content-Type: {{contentType}}

{
	"price": "{{price}}",
	"title":"{{title}} 2",
	"image":"{{image}}",
	"link":"{{link}}",
	"percentage": "{{percentage}}"
}

###
GET {{baseUrl}}/products/{{productId}}
Content-Type: {{contentType}}

###
DELETE {{baseUrl}}/products/{{productId}}
Content-Type: {{contentType}}
